### ISSUE TITLE
Integer overflow for big numbers in JSON

### ISSUE THREAD

**Issue by Drarig29** [ArthurSonzogni/json-tui#2]
I was working with Unix timestamps, and the displayed number is incorrect. It looks like an integer overflow.

```json
{
  "big": 1640267163452
}
```

What is displayed:

```json
{
  "big": -410343620
}
```

**Comment by ArthurSonzogni** [comment]
Interesting. I will take a look how to make nlohmann/json to return the right value as a string.

**Comment by ArthurSonzogni** [comment]
It has been fixed. Thanks for reporting this!
