### ISSUE TITLE
Add possibility to unroll and collapse all structured data in selected column at once in table view

### ISSUE THREAD

**Issue by prajnoha** [ArthurSonzogni/json-tui#25]
If we're in table view and if we have json input that contains structured data (arrays, objects...) in certain columns, then by default, the arrays are collapsed and one needs to press "Mouse::Left" or "enter" for each such value in the column to have them all unrolled. It would be very practical to have a single keybinding that would unroll all such values in currently selected column at once (and vice-versa - to collapse them all at once).

**Comment by ArthurSonzogni** [comment]
Maybe +/- will unroll/roll at least one more nested level. This sounds like a nice feature. Thanks for the suggestion!
