### ISSUE TITLE
Hitbox issue when not on top of the terminal window

### ISSUE THREAD

**Issue by Drarig29** [ArthurSonzogni/json-tui#7]
Sorry if I'm being annoying, but I found a hitbox bug. The video explains it all.

Basically, after I hit Ctrl+C and re-run the command, the hitboxes are shifted away from their real location.

I really think it's because the command isn't run from the top of the window.

Could someone test this in his terminal? Maybe the bug comes from my terminal emulator actually... I use https://github.com/kovidgoyal/kitty

Here is the example file I used: https://pastebin.com/HxCY0NUm

https://user-images.githubusercontent.com/9317502/148837469-363681d8-5379-42fb-a3ca-5758a5a61f3f.mp4

**Comment by ArthurSonzogni** [comment]
Thanks!

Yes, I observed it. I should update the underlying library to request a refresh of the position earlier.

**Comment by ArthurSonzogni** [comment]
I think I fixed it. Could you please check again whether this is working or not according to you?
Don't forget to remove your build directory, in order to force fetching FTXUI again.

**Comment by Drarig29** [comment]
Yup, it's fixed! You are reactive too! 😁

And thanks for the reminder to remove the build directory, I was going to say it didn't work ^^

**Comment by ArthurSonzogni** [comment]
> And thanks for the reminder to remove the build directory, I was going to say it didn't work ^^
Haha, I edited my last response just in time then.

Thanks for your confirmation!
