### ISSUE TITLE
Resize to full terminal screen

### ISSUE THREAD

**Issue by Dentrax** [ArthurSonzogni/json-tui#9]
Thanks for such a great tool! I've been trying to give some feedback.

---

Like how [fx](https://github.com/antonmedv/fx) already does, we can resize the output to full terminal screen by passing a flag or by default.

Current behavior:
![Screen Shot 2022-01-11 at 12 00 30](https://user-images.githubusercontent.com/16493751/148912189-8eaa6d88-22fd-4bb0-9613-76cab3bf0ea7.png)

Press `q` to exit. Wdyt?

**Comment by ArthurSonzogni** [comment]
> Thanks for such a great tool! I've been trying to give some feedback.

Thanks!

> Like how fx already does, we can resize the output to full terminal screen by passing a flag or by default.

It is just a matter of swapping:
https://github.com/ArthurSonzogni/json-tui/blob/5a223aab989d7d46cd59e68c3c2dec7b7eea1168/src/main.cpp#L217
into:
```cpp
  auto screen = ScreenInteractive::Fullscreen();
```

I see the ability to display the json inline to be a feature. I don't mind adding the capability to do both. Do you think I should allow users to configure it? Maybe a config.json file or some flags.
```
.config/json-tui/config.json
```
```json
{
  "display": "fullscreen",
  "colors": {
    "number": "red",
    "string": { "r": 255, "g": 0, "b": 0}
    "boolean": { "h": 255, "s": 0, "v": 0}
  },
  "key": {
    "quit": "q"
  },
  "autoexpand-depth": {
    "object": 1
    "array": 0
  }
}
```

> Press q to exit. Wdyt?

Haha, yes, that would be nice indeed!

**Comment by Dentrax** [comment]
> Maybe a config.json file or some flags.

`config.json` would be a bit overengineering in this context. Probably passing a flag better idea.

> I see the ability to display the json inline to be a feature.

If you want to display the JSON inline by default, then we can add smth `--fullscreen` flag to change _ScreenInteractive_ mode.
